### ISSUE TITLE
Separate source files for cluster management

### ISSUE THREAD

**Issue by nmraz** [ThatFatPat/BSFS#8]
The cluster/bitmap management API has grown considerably in size since its inception. In fact, it is now so large that we might want to consider moving the cluster API to its own file - I think that `fuse_ops` should be concerned just with interfacing with FUSE, not with miscellaneous filesystem operations.

Any thoughts on this?

**Comment by ThatFatPat** [comment]
I agree. Sounds like a decent idea to me. Please remember to link fuse_ops and the new file in CMake.

**Comment by eyalnesher** [comment]
That sounds right.

**Comment by nmraz** [comment]
Fixed in ea1882d1696f09f696e1a60b28f5d62bf4814b42.
